[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sergei Radutnuy <sergeiradutnuy01@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.6"
docopt = "1.0"
image = "0.21"
num = "0.2"
num_cpus = "1.9.0"
serde = "1.0"
serde_derive = "1.0"
